import { SectionNameDiv } from './style'
export const Header = () => {

  return (
    <SectionNameDiv>
      <section>
        <div className='line'>
          <h1 className='lineUp'>Hi, my name is Jonatas,</h1>
          <h1 className='lineUp'>and i'm a <b>FullStack Developer</b></h1>
        </div>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p><p>aaaaaa</p>
        <p>aaaaaa</p>
        <p>aaaaaa</p>

      </section>
    </SectionNameDiv>
  )
}
